### ISSUE TITLE
Одновременная проверка в нескольких чатах может не сработать корректно

### ISSUE THREAD

**Issue by shsmad** [krddevdays/bot#6]
Если запущен один инстанс бота на несколько чатов, то у них будет общий `krddevbot/antispam.py:CHECKING_MEMBERS`.

Есть подозрение, что в случае, когда один и тот же пользователь ломанется в несколько чатов, в которых дежурит бот, код 

```py
CHECKING_MEMBERS[user.id] = {
       'message_id': sent_msg.id, 
       'emoji': EMOJI[challenge_text],
}
```

сработает не так, как ожидается. 

Возможно стоит заменить на `CHECKING_MEMBERS[f"{user.id}_{update.effective_chat.id}"]`?

**Comment by brunql** [comment]
Согласен, нужно привязывать пользователя к чату, будем править.

**Comment by TyVik** [comment]
FYI я переделал на `CHECKING_MEMBERS[f"{user.id}_{update.effective_chat.id}_{sent_msg.id}"] = EMOJI[challenge_text]`
