### ISSUE TITLE
Баг с нижним подчёркиванием в username и его отсутствием

### ISSUE THREAD

**Issue by iscandero** [krddevdays/bot#7]

**Comment by brunql** [comment]
В общем кажется, что кое-кто с доступом к серверному телу внес несколько `escape_markdown `и никому не сказал.

В целом это правильно, но не во всех сообщениях используется `parse_mode=ParseMode.MARKDOWN_V2` поэтому и работает по разному.

**Comment by agorozhanin** [comment]
https://github.com/krddevdays/bot/pull/9

**Comment by TyVik** [comment]
Да, поздно вечером было дело. Не проверил, что правильный парсер везде стоит. Сегодня-завтра залью обновления.
